name: Multicluster test

on:
  [workflow_dispatch, push]
jobs:
  k3d-inspect:
    name: Multi cluster on the common bridge network
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        name: "test-cluster-1 on bridge network"
        with:
          k3d-name: "test01"
          k3d-args: "-p \"80:80@agent[0]\" -p \"443:443@agent[0]\" -p \"5053:53/udp@agent[0]\"  --agents 3 --no-lb --k3s-server-arg \"--no-deploy=traefik,servicelb,metrics-server\" --network bridge"
      - uses: ./
        name: "test-cluster-2 on bridge network"
        with:
          k3d-name: "test02"
          k3d-args: "-p \"81:80@agent[0]\" -p \"444:443@agent[0]\" -p \"5054:53/udp@agent[0]\"  --agents 3 --no-lb --k3s-server-arg \"--no-deploy=traefik,servicelb,metrics-server\" --network bridge"
      - run: kubectl cluster-info
      - run: docker ps -a
      - run: docker network inspect bridge
