apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1
  labels:
    app: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
        - name: test1-app
          image: registry.localhost:5000/aaa:v0.0.1
