name: k3d-test

on:
  [ workflow_dispatch, push ]

jobs:
  some-job:
    name: Inspect
    runs-on: ubuntu-latest
    steps:
      - uses: nolar/setup-k3d-k3s@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: v1.19.4
          k3d-name: test-gslb1
