name: Multicluster test

on:
  [workflow_dispatch, push]
jobs:
  k3d-inspect:
    name: Multi-cluster test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: kuritka/k3d-action@v1.0.1
        name: "Create 1st k3d Cluster with Registry"
        with:
          k3d-name: "test-cluster-1"
          k3d-registry: true
          k3d-args: >-
            --agents 1
            --no-lb
            --k3s-server-arg "--no-deploy=traefik,servicelb,metrics-server"
      - uses: kuritka/k3d-action@v1.0.1
        name: "Create 2nd k3d Cluster with Registry"
        with:
          k3d-name: "test-cluster-2"
          k3d-registry: true
          k3d-args: >-
            --agents 1
            --no-lb
            --k3s-server-arg "--no-deploy=traefik,servicelb,metrics-server"

      - name: Nodes
        # hack, wait until agents are ready.
        run: |
          docker ps -a
          kubectl config use-context k3d-test-cluster-1
          sleep 5
          kubectl get nodes -o wide
          kubectl config use-context k3d-test-cluster-2
          kubectl get nodes -o wide

      - run: |
          GO111MODULE=on go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.32.0
          export PATH=~/go/bin:$PATH
          make

