name: SimpleTest

on:
  [workflow_dispatch, push]
jobs:
  k3d-inspect:
    name: SIMPLE test
    runs-on: ubuntu-latest
    steps:
      - uses: AbsaOSS/k3d-action@downgrade
        name: SIMPLE
        with:
          cluster-name: "cmak"
          args: >-
            --no-lb
            --k3s-server-arg "--no-deploy=traefik,servicelb,metrics-server"
      - run: sleep 3 && kubectl get nodes
