name: SimpleTest

on:
  [workflow_dispatch, push]
jobs:
  k3d-inspect:
    name: Multi-cluster test
    runs-on: ubuntu-latest
    steps:
      - uses: AbsaOSS/k3d-action@v1.3.0
        name: create cluster
        with:
          cluster-name: "cmak"
          args: --config=k3d.yaml
      - run:
          kubectl get nodes
